### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#545] opened 2016-12-23 18:37 UTC
To be discussed

- Define Api
- Implement Api

**Comment by jjlauer** [comment] 2016-12-23 18:40
Some early investigation of websockets & what an API could look like was done here:

https://github.com/fizzed/ninja/tree/feature_websocket

Discussion from mailing list worth copying here for context as well:

I initially thought that JSR356 as a standard meant getting websocket support in servlet containers & Ninja would be an easy effort.  The problem is that JSR356 is somewhat poorly designed, especially with letting you control the upgrade/handshake process.  I also wanted to let non-servlet containers such as 'ninja-undertow` https://github.com/fizzed/ninja-undertow be able to supply WebSockets to ninja w/o servlets.

Here's what I brainstormed for an api.  When setting up your routes, it would look like this:

```java
public class Routes implements ApplicationRoutes {
    @Override
    public void init(Router router) {
        // using new Java-8 style method references
        router.GET().route("/").with(ApplicationController::index);
        router.WS().route("/ws").with(ApplicationController::websocket);
    }
}
```

Then in `application.websocket()` you would be able to get any parameters injected via guice just like any other controller method for the initial handshake.  Then you would have filters run, reject the handshake, etc.  I think we'd need to have a special WebSocketResult returned that is the underlying connection handler if its connected.  Anything other than a WebSocketResult would mean the handshake should be rejected/fallback to HTTP.

I got `ninja-standalone` to enable websockets via Jetty, and the route itself actually is added, but that's as far as I got.  I had to move onto other projects for the time being.  But if anyone wanted to continue the effort in the meantime, I'd be happy to help map it out.

**Comment by bhuvangu** [comment] 2017-05-26 04:43
Hello good people... Are there any active plans to include this in ninja

**Comment by joshkamau** [comment] 2017-06-14 11:03
Waiting for the answer to the above ^^ ;)

**Comment by davidgiga1993** [comment] 2017-08-22 18:44
Any update on this? A jetty  based implementation with ninja-standalone would be enough for my use case. If not I would try to continue your implementation as far as I got time. Which points were still open in your implementation?

**Comment by jjlauer** [comment] 2017-08-22 18:55
@davidgiga1993 If you look at https://github.com/ninjaframework/ninja/compare/develop...fizzed:feature_websocket -- I had a rough version working.  If someone wanted to use that as a base, I'd be glad to help/guide them.

**Comment by jjlauer** [comment] 2017-08-29 21:55
@davidgiga1993 @joshkamau @bhuvangu I had a few days of time to spending polishing up what I have previously tried.  I now have a fairly complete websockets implementation finished for ninja.

https://github.com/fizzed/ninja/tree/feature/websocket

Sample routes:

https://github.com/fizzed/ninja/blob/feature/websocket/ninja-servlet-integration-test/src/main/java/conf/Routes.java

Sample endpoint:

https://github.com/fizzed/ninja/blob/feature/websocket/ninja-servlet-integration-test/src/main/java/controllers/ChatWebSocket.java

Based on JSR-356 support in Jetty, Tomcat, Wildfly, etc.  Now, JSR-356 has a few design flaws, but this impl includes a way of getting the original handshake headers in Ninja :-)

What's missing?  User feedback, more documentation, unit tests, and possibly more Ninja abstractions to help get injected values (e.g. the Ninja session).  I guess I'd say this gets us fairly standard JSR-356 endpoints.

Would love to know what you think.

**Comment by davidgiga1993** [comment] 2017-08-30 09:17
Wow, that was fast!

should the sample route and endpoint already work?
I've tried with the python websockets-client but only get a 404 using the defined route:
```
--- request header ---
GET /chat HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:8080
Origin: http://localhost:8080
Sec-WebSocket-Key: LSnAtmHlDRGa3Bk8OhAnOg==
Sec-WebSocket-Version: 13

--- response header ---
HTTP/1.1 404 Not Found
Date: Wed, 30 Aug 2017 09:03:23 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Server: Jetty(9.3.11.v20160721)
```
or am I missing something obvious here? (Yes I've checked out the websocket branch :-) )

**Comment by jjlauer** [comment] 2017-08-30 13:17
Hmm.. Jetty 9.3.15+ is the latest my branch uses but yours says 9.3.11.  I'm guessing something must not be totally up-to-date. Let's sanity check you've got the latest stuff.  Fresh checkout, etc.

```
git clone https://github.com/fizzed/ninja ninja-fizzed
cd ninja-fizzed
git checkout feature/websocket
mvn install -DskipTests=true
cd ninja-servlet-integration-test
mvn jetty:run
```

Then in your python client, you'd want to connect to `ws://localhost:8080/chat` -- the jetty version in the headers you see should say 9.3.15.  Also, the route dump when ninja starts should have a "WS /chat" in it too.  Let me know how it goes!

**Comment by davidgiga1993** [comment] 2017-08-31 06:28
Ah, using `jetty:run` instead of `ninja:run` fixed the issue.
I'll start playing around now and let you know how it works.

**Comment by jjlauer** [comment] 2017-09-01 14:41
PR #582 submitted.  Any questions/feedback would be great.

**Comment by jjlauer** [comment] 2017-09-14 17:46
Feature merged and will be shipped in next release.

**Closed as completed by jjlauer** 2017-09-14 17:46 UTC
Labels: enhancement

**Comment by joshkamau** [comment] 2017-09-15 08:10
Yayyy! Thanks alot guys.... You just saved me from spring
