### ISSUE TITLE
udpcount route doesn't work

### ISSUE THREAD

**Issue by arusland** [ninjaframework/ninja#92] opened 2013-05-15 20:21 UTC
I've generate project through maven 

**mvn archetype:generate -DarchetypeGroupId=org.ninjaframework -DarchetypeArtifactId=ninja-core-demo-archetype**

After run this project by jetty **/udpcount** cannot be accessed. Although udp listener had started. Log doesn't contain any error.

**Java Version:** 1.7.0.21
**OS:** Windows 7 x64

**Comment by raphaelbauer** [comment] 2013-05-16 17:07
Hi and thanks for the bugreport...

you are right. The problem is that the return method should be like return Results.json().render(count.get()); and NOT Results.json(count.get()). If you change that it will work.

I'll mark that as bug, and we should fix that for the next release (plus a testcase :) ).

Thanks!

Cheers,

Raphael

**Comment by arusland** [comment] 2013-05-16 17:20
Hello Raphael,

Yes, that line works)

Best regards,
Ruslan A.

**Comment by raphaelbauer** [comment] 2013-05-19 17:56
this is fixed in develop :) will be pushed to maven central with the next release...

**Closed as completed by raphaelbauer** 2013-05-19 17:56 UTC
Labels: bug
