### ISSUE TITLE
Weird behavior of UnitOfWork: breaks Transactional

### ISSUE THREAD

**Issue by nobullet** [ninjaframework/ninja#185] opened 2014-06-06 00:08 UTC
UnitOfWork caches the retrieved values from EntityManager somewhere (seems like thread local of threads in Jetty's pool) even if the database's cache is disabled completely.

Here is the repo of the project to reproduce: https://github.com/nobullet/unitofwork-transactional

The heart of the app is UserService: 
 a) it loads an User object from database (or creates new if not found), increments its field #visited and saves it back to database each second (#doStuffEachSeconds) in @Transactional method.

 b) it has 2 methods that do the same thing: query the User object by name.
    **getUserOneUOW**  - is **@UnitOfWork** annotated
    **getUserOneT**  - is **@Transactional** annotated

 c) ApplicationController has two methods to render the retrieved objects to JSON (with no-cache headers): one calls UserService#getUserOneUOW, the other calls UserService#getUserOneT

**Steps to reproduce:**
1. clone the aforementioned repo
2. cd to the folder of the repo
3. chmod +x ./standalone_dev.sh
4. ./standalone_dev.sh    (this will start simple Ninja app in standalone mode with H2 database with completely disabled database cache - see persistence.xml, reproducible in MySQL too).
5. When app starts you should see the warn messages like about saved User entity with name one and the current value of visited field:
   01:38:55.350 WARN  Ninja.useCase [48] - User one visited: 51 times, 1 users in database. [pool-1-thread-1]
   01:38:55.350 WARN  Ninja.useCase [48] - User one visited: 52 times, 1 users in database. [pool-1-thread-1]
   etc
6. Open this url **http://localhost:8081/test/userT.json** - **@Transactional** method, in browser, run several times. Switch back to the console and make sure the url returns same results for **#visited** field as in logs (console) and database. 
   At this point we are using **@Transactional** method and everything is fine. 
7. Now open **http://localhost:8081/test/userUOW.json** - **@UnitOfWork** method and run it several times (> than number of cores that your processor has). 
   It will start to return cached values (depends on thread from Jetty's thread pool) and while **UserService#doStuffEachSeconds** continues to increment the returned entities are cached and have obsolete #visited values.
   The returned User instances are cached somewhere (like thread locals in Jetty's threads).
8. If you switch back and try to run **@Transactional** method (6) it will start to return same cached values as (7): UnitOfWork has broken the Transactional behavior.

mvn -version
Apache Maven 3.1.1 (hashcode; 2013-09-17 08:22:22-0700)
Maven home: /Users/nb1967/bin/maven
Java version: 1.8.0, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.2", arch: "x86_64", family: "mac"

sysctl hw.ncpu | awk '{print $2}'   # number of cores
8

**Comment by raphaelbauer** [comment] 2014-06-06 19:28
(copied from the mailing list)
Thanks for the report! Do you think it would be possible to write one
testcase that reproduces the problem? Then we can make sure the
regression does not happen in future versions of Ninja.

Two thoughts:
1. As workaround you can use @Transactional everywhere (the default
approach). This will work.
2. Ninja will most likely move on to http://onami.apache.org/persist/
. Onami works the same way as guice-persist, but supports more than
one database out of the box and also a built-in @UnitofWork.

Cheers,

Raphael

**Comment by nobullet** [comment] 2014-06-06 23:17
Will try to think about the test: seems to be tricky...

**Comment by cpisto** [comment] 2014-08-07 02:01
Has this been confirmed as an issue with ninja itself?

**Comment by nobullet** [comment] 2014-08-07 06:24
Well, I can confirm that the bug is still here for Ninja 3.3.0.
I don't know if anyone tried to fork this bug's repo and reproduce.
Judging by Raphael's reply, I suppose he tried to reproduce it.

**Comment by cpisto** [comment] 2014-08-07 06:26
I've def reproduced the issue with your repo.

**Comment by cpisto** [comment] 2014-08-07 14:20
I added a call to logger.info("EntityManager.id " + System.identityHashCode(em)); inside UserDao.getByName.

After the first request for userUOW.json the same EntityManager instance is returned for every following request, so the @UnitOfWork interceptor is not ending the UnitOfWork. Any subsequent @UnitOfWork or @Transactional on the same thread will get the same EntityManager and cache state.

Stepping through it in the debugger, during a request for userUOW.json, the UnitOfWork interceptor always goes through the path that skips the begin/end, I'm not sure why yet.

**Comment by cpisto** [comment] 2014-08-07 16:22
Seems like the UnitOfWork Interceptor is just wrong, I don't follow why there is the entityManagerProvider.get() == null check. Won't it always fail since entityManagerProvider.get() should always return the JpaPersistService instance bound at ninja startup in JpaInitializer? The UnitOfWorkInterceptor code mentions its mimicking JpaLocalTxnInterceptor, but JpaLocalTxnInterceptor uses !emProvider.isWorking() as its check, not emProvider == null..

@raphaelbauer any thoughts?

**Comment by nobullet** [comment] 2014-08-07 17:18
Unfortunately, Guice's isWorking() is doing the same thing:

public boolean isWorking() {
    return entityManager.get() != null;
}

**Comment by cpisto** [comment] 2014-08-07 17:23
Whatever the bug might actually be, as it is now, entityManagerProvider.get() == null never evaluates to true in UnitOfWorkInterceptor, so didWeStartWork is never set to true which means end() never get called and end() is where EntityManger.close() happens.

EntityManager will be the same instance (with the same unflushed "first-level" cache) across requests on the same thread until close() is called

**Comment by nobullet** [comment] 2014-08-07 17:32
Need to check that.

By the way: I've added **getUserOneNTNUOW** method to the service.
It does not use **Transactional** nor **UnitOfWork**. 
With just a pair of methods **getUserOneNTNUOW** and **getUserOneT** I was able to reproduce the issue. Seems that the problem might not be related to **UnitOfWork**.

**Comment by cpisto** [comment] 2014-08-07 17:36
Without @Transactional _or_ @UnitOfWork you never get EntityManager.close() called which results in the same EntityManager instance living on through all requests on the same thread.

You absolutely need one or the other, and right now UnitOfWorkInterceptor is not calling end() so it effectively behaves the same as a method with no UnitOfWork annotation in the first place.

**Comment by cpisto** [comment] 2014-08-07 18:38
The change introduced just before 3.1.0 is what broke things.

The intention of the change was to allow ( per https://github.com/ninjaframework/ninja/issues/157 )

@Transactional 
@UnitOfWork

but the guice persist docs say you can only do ( per https://github.com/google/guice/wiki/Transactions#units-of-work )

@UnitOfWork
@Transactional

And the change made it so @UnitOfWork does nothing (per above discussion)

@nobullet have you tested with a ninja version before 3.1.0?

**Comment by cpisto** [comment] 2014-08-07 18:40
I just tested with 3.0.3 and everything works as expected.

**Comment by nobullet** [comment] 2014-08-07 18:44
I do confirm that 3.0.0 works too. Thank you, cpisto. I think you have found the reason of the bug! :)

**Comment by nobullet** [comment] 2014-08-07 19:01
Well, the fix is to rollback the **fix-157**, as this pattern is not supported by Guice-Persist (and the order does not make sense to me at least).

@Transactional
@UnitOfWork 

This also needs a proper documentation as right now is it hard to understand, why and when use **@UnitOfWork** vs **@Transactional**.

This is my understanding but this is must be confirmed:
1. Read-only queries per request scenario: use **@UnitOfWork**
2. Write queries: use **@Transactional** around
3. Several transactions per request: **@UnitOfWork** can contain several transactions but this is not obligatory to have **@UnitOfWork** around transactions.

Please correct me if I'm wrong.

**Comment by cpisto** [comment] 2014-08-07 19:02
All of that is correct.

**Comment by raphaelbauer** [comment] 2014-08-09 11:47
Hey... 

really cool that you found the issue!
Is there anything where I can help?

As I understand three things should be done:
- Fix bug in Ninja (rollback the change of #157)
- Add documentation to Ninja to highlight when UnitOfWork should be used
- Add testcase that tests against the bug here

Did you fix already anything? Otherwise I'd schedule the fix and implement that hopfully the coming days.

Apart from that: Guice-persist will be dead at some point. That's not bad, because there is a great alternative: http://onami.apache.org/persist/

I'd love to replace guice-persist with onami at some point...

Thanks for you help figuring that out! Very well done!

Raphael

**Comment by nobullet** [comment] 2014-08-09 20:27
Hi, Raphael.

I don't think any of us have started to fix the issue: in my opinion I would be better if you fix/rollback that CL. Just because you are the author of the original fix #157 and you know more about it.

I can document the usage of the **@UnitOfWork** and **@Transactional** and use my comment above as the base:
1. Read-only queries in the request scenario: use **@UnitOfWork** around the controller or service method.
2. One or more write queries in the request: use **@Transactional** around the controller or service method.
3. Several write queries in the several transactions in the same request: 
   - a. use **@UnitOfWork** around the controller or service method and use **@Transactional** or programmatic API of the EntityManager to demarcate transaction within the same **@UnitOfWork**
   - b. use  **@Transactional** or programmatic API of the EntityManager to demarcate transaction within the same request without **@UnitOfWork**

The test is hard to write because this is a concurrent issue and hardware dependent: number of cores changes the behavior.

I also think that the planned switch to Onami should happen in major version of Ninja (like 4.0.0).
This switch requires Ninja's users to change persistence configuration.

**Comment by raphaelbauer** [comment] 2014-08-09 21:04
Regarding documentation. Is the following a short version of what you've said?

"For read-only queries you should use @UnitOfWork (and it may be faster because there are no transactions started). But for saving / updating and deleting data always use @Transactional."

=> because that version is already on the homepage. Or in other terms: Have a look at http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html - is that ok - or should it be clarified?

... and regarding onami => yes. I totally agree that this should happen in a major version. Switching must be painless - and there should be a simple upgrade path

Thanks for your efforts!

**Comment by raphaelbauer** [comment] 2014-08-09 21:12
I reverted the commit. Would you mind having a look at: https://github.com/ninjaframework/ninja/pull/208

Does this fix the issue for you?

**Comment by cpisto** [comment] 2014-08-09 21:16
Looks correct to me.

**Comment by nobullet** [comment] 2014-08-10 05:42
Hi, Raphael.

Thanks for your response. The documentation was greatly improved. 

I would also ask you to add a small clarification about usage of the combination of **@UnitOfWork** and **@Transactional**: the allowed case (several  **@Transactional** inside the **@UnitOfWork**) and forbidden case (nested **@UnitOfWork**).

I would also ask you to fix the disambiguation (in my opinion) about **transaction-type=RESOURCE_LOCAL**.
It is due to fact that Ninja is responsible for setting up/shutting down the JPA's EntityManagerFactory and 
EntityManagers. In **JTA** transactions EntityManagers are injected/managed by JEE containers which is not possible in Ninja. Good and short description is here:
http://stackoverflow.com/questions/17331024/persistence-xml-different-transaction-type-attributes

**Comment by raphaelbauer** [comment] 2014-08-10 07:59
Hey @nobullet ,

sounds very good - simple idea: You can edit and improve the docs online yourself: https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/site/markdown/documentation/working_with_relational_dbs/jpa.md

That's really convenient... It would be cool if you could add your improvements. I'll then cut a new bugfix release and put the new docu online :) Would that work?

Thanks! Raphael

**Comment by raphaelbauer** [comment] 2014-08-10 15:43
... just a quick clarification... You can improve the docs without checking out code or touching git ... github let's you edit the file online... You can improve and copy and paste your ideas :)

**Comment by nobullet** [comment] 2014-08-10 20:07
Hi, @raphaelbauer and @cpisto .

Please review the pull request (documentation changes): https://github.com/ninjaframework/ninja/pull/209

Thanks.

**Comment by raphaelbauer** [comment] 2014-08-11 19:01
Okay... I merged the PR and incorporated @nobullet 's doc improvements. Will cut bugfix release now. Awesome work! Thanks for figuring out the problem :)

**Closed as completed by raphaelbauer** 2014-08-11 19:01 UTC
Labels: bug
