### ISSUE TITLE
changed java versions and got

### ISSUE THREAD

**Issue by eagwasim** [ninjaframework/ninja#605] opened 2018-02-28 15:49 UTC
java.lang.RuntimeException: javax.crypto.BadPaddingException: Given final block not properly padded
	ninja.utils.CookieEncryption.decrypt(CookieEncryption.java:139)
	ninja.session.SessionImpl.init(SessionImpl.java:117)
	ninja.utils.AbstractContext.init(AbstractContext.java:95)
	ninja.servlet.NinjaServletContext.init(NinjaServletContext.java:128)
	ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:82)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)

**Comment by jjlauer** [comment] 2018-02-28 15:57
This seems to be a duplicate of https://github.com/ninjaframework/ninja/issues/532

There a fix included in Ninja awhile ago for this -- what version of Ninja are you running?

**Comment by eagwasim** [comment] 2018-02-28 16:07
5.8.0

**Comment by jjlauer** [comment] 2018-02-28 16:16
That issue is fixed per #532 .  You'll either want to install the JCE extension to your new Java install or bump the Ninja version up to take care of it.  Or both.

**Closed as completed by jjlauer** 2018-02-28 16:16 UTC
