### ISSUE TITLE
Help with Hello World app

### ISSUE THREAD

**Issue by ufmemo** [ninjaframework/ninja#407] opened 2015-10-06 03:35 UTC
We're in the process of evaluating lightweight Java web frameworks for Java & GAE.  The Ninja framework documentation indicates this is a great fit.  I have spent three full days trying to get a basic hello world styled app to run on GAE but haven't been able to get past this issue.

Uncaught exception from servlet
java.lang.ExceptionInInitializerError
    at org.slf4j.LoggerFactory.reportMultipleBindingAmbiguity(LoggerFactory.java:259)
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:139)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
    at ninja.utils.NinjaPropertiesImpl.<clinit>(NinjaPropertiesImpl.java:40)
    at ninja.servlet.NinjaServletListener.getInjector(NinjaServletListener.java:103)

I've tried to remove every reference to slf4j but no luck.  Any help would be much appreciated.  I've used the maven archetype for the GAE Blog application, created a basic GAE app and then imported all the Ninja dependencies, both yield the same frustrating results. 

Thanks for the help in advance.

**Comment by lazaridis-com** [comment] 2016-01-25 09:53
@ufmemo , is this issue still of relevance for you?

**Comment by ufmemo** [comment] 2016-01-25 19:03
Unfortunately, I never solved this issue and decided to try an alternative.

**Comment by lazaridis-com** [comment] 2016-01-26 11:04
@raphaelbauer , any hints here? Shouldn't the archetype work out-of-the-box?

**Comment by raphaelbauer** [comment] 2016-01-27 14:56
1) That's a question related to the ninja-gae plugin... and second this was caused by a bug in log4j which is fixed by now. So it should work again :)

**Closed as completed by raphaelbauer** 2016-01-27 14:56 UTC
